AWSTemplateFormatVersion: "2010-09-09"
Parameters:
  Password:
    Type: String
  Environment:
    Type: String
    Default: "dev"
    Description: "Environment name for resource uniqueness"

Resources:
  OneTimePassword:
    Type: AWS::SecretsManager::Secret
    DeletionPolicy: Delete
    UpdateReplacePolicy: Delete
    Properties:
      Name: !Sub "OneTimePassword-v5-${Environment}-${AWS::Region}"
      SecretString: !Sub '{"password":"${Password}"}'

  S3UserGroup:
    Type: AWS::IAM::Group
    Properties:
      GroupName: !Sub "S3UserGroupV5-${Environment}"

  S3UserGroupPolicy:
    Type: AWS::IAM::Policy
    Properties:
      PolicyName: !Sub "S3ReadOnlyAccessPolicy-v5-${Environment}"
      Groups:
        - Ref: "S3UserGroup"
      PolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: "Allow"
            Action:
              - "s3:ListBucket"
              - "s3:GetObject"
            Resource: "*"

  EC2UserGroup:
    Type: AWS::IAM::Group
    DeletionPolicy: Delete
    UpdateReplacePolicy: Delete
    Properties:
      GroupName: !Sub "EC2UserGroup-v5-${Environment}"

  EC2UserGroupPolicy:
    Type: AWS::IAM::Policy
    Properties:
      PolicyName: !Sub "EC2ReadOnlyAccessPolicy-v5-${Environment}"
      Groups:
        - Ref: "EC2UserGroup"
      PolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: "Allow"
            Action:
              - "ec2:DescribeInstances"
            Resource: "*"

  EC2User:
    Type: AWS::IAM::User
    Properties:
      UserName: !Sub "ec2-user-v5-${Environment}"
      Groups:
        - Ref: "EC2UserGroup"
      Tags:
        - Key: "email"
          Value: "rossieEC2@gmail.com"

  S3User:
    Type: AWS::IAM::User
    Properties:
      UserName: !Sub "s3-user-v5-${Environment}"
      Groups:
        - Ref: "S3UserGroup"
      Tags:
        - Key: "email"
          Value: "rossieS3@gmail.com"

  EventBridgeRule:
    Type: AWS::Events::Rule
    Properties:
      Name: !Sub "NewUserCreationRule-v5-${Environment}"
      EventPattern:
        source:
          - "aws.iam"
        detail-type:
          - "AWS API Call via CloudTrail"
        detail:
          eventName:
            - "CreateUser"
      Targets:
        - Arn: !GetAtt "LambdaFunction.Arn"
          Id: "LambdaFunctionTarget"

  LambdaFunction:
    Type: AWS::Lambda::Function
    DeletionPolicy: Delete
    UpdateReplacePolicy: Delete
    Properties:
      FunctionName: !Sub "LogUserCreation-v5-${Environment}"
      Handler: "org.rossie.LogUserLambda::handleRequest"
      Role: !GetAtt "LambdaExecutionRole.Arn"
      Runtime: "java17"
      Code:
        S3Bucket: "bucket1-7nyh"
        S3Key: "Automating_IAM_Creation-1.0-SNAPSHOT.jar"
      Environment:
        Variables:
          ENVIRONMENT: !Ref Environment
          CUSTOM_REGION: !Ref "AWS::Region"
      Timeout: 30
      MemorySize: 512

  LambdaExecutionRole:
    Type: AWS::IAM::Role
    Properties:
      RoleName: !Sub "LogUserCreationRole-v5-${Environment}"
      AssumeRolePolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: "Allow"
            Principal:
              Service: "lambda.amazonaws.com"
            Action: "sts:AssumeRole"
      ManagedPolicyArns:
        - "arn:aws:iam::aws:policy/service-role/AWSLambdaBasicExecutionRole"
      Policies:
        - PolicyName: !Sub "LogUserCreationPolicy-v5-${Environment}"
          PolicyDocument:
            Version: "2012-10-17"
            Statement:
              - Effect: "Allow"
                Action:
                  - "secretsmanager:GetSecretValue"
                  - "cloudtrail:LookupEvents"
                  - "iam:ListUserTags"
                Resource: "*"
              - Effect: "Allow"
                Action:
                  - "s3:GetObject"
                Resource: !Sub "arn:aws:s3:::bucket1-7nyh/*"

  LambdaPermission:
    Type: AWS::Lambda::Permission
    Properties:
      Action: "lambda:InvokeFunction"
      FunctionName: !Ref LambdaFunction
      Principal: "events.amazonaws.com"
      SourceArn: !GetAtt EventBridgeRule.Arn